---
spring:
  application:
    name: eureka-server-clustered
  profiles: primary
server:
  port: 8762

eureka:
  instance:
    hostname: eureka-primary
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka-secondary:8763/eureka/,http://eureka-tertiary:8764/eureka/
---

spring:
  application:
    name: eureka-server-clustered
  profiles: secondary
server:
  port: 8763

eureka:
  instance:
    hostname: eureka-secondary
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka-primary:8762/eureka/,http://eureka-tertiary:8764/eureka/
---

spring:
  application:
    name: eureka-server-clustered
  profiles: tertiary


server:
  port: 8764
eureka:
  instance:
    hostname: eureka-tertiary
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka-secondary:8763/eureka/,http://eureka-primary:8762/eureka/

